2021-08-28 10:49:20,807 ERROR: Exception on /admin [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1728, in make_response
    "The view function did not return a valid"
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a BaseQuery.
2021-08-28 10:49:32,302 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 10:52:18,400 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 10:52:19,936 ERROR: Exception on /admin [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 16, in admin
    return jsonify({"items": users})
NameError: name 'jsonify' is not defined
2021-08-28 10:52:50,540 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 10:52:52,096 ERROR: Exception on /admin [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 17, in admin
    return jsonify({"items": users})
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 56, in default
    return super().default(o)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type User is not JSON serializable
2021-08-28 10:55:01,320 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 10:55:33,779 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 10:55:36,404 ERROR: Exception on /admin [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 19, in admin
    return jsonify({"items": all_users})
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 348, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 129, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\json\__init__.py", line 56, in default
    return super().default(o)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
2021-08-28 11:01:17,242 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:02:36,301 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:03:14,991 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:04:12,077 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:05:36,164 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:07:40,688 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:08:35,415 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:10:58,034 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-08-28 11:11:05,618 ERROR: Exception on /admin [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 28, in admin
    return render_template('admin.html', all_users=all_users)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\onely\app\templates\admin.html", line 35, in top-level template code
    {%for i in range(0, len)%}
TypeError: 'Undefined' object cannot be interpreted as an integer
2021-08-28 11:12:35,441 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
