2021-09-29 12:27:00,015 ERROR: Exception on /liverequests [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 55, in liverequests
    return render_template('liverequests.html', all_requests=all_requestss)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\onely\app\templates\liverequests.html", line 6, in top-level template code
    <link rel="stylesheet" href="{{ url_for('', filename='styles.css') }}">
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '' with values ['filename']. Did you mean 'bootstrap.static' instead?
2021-09-29 12:27:04,452 ERROR: Exception on /liverequests [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 55, in liverequests
    return render_template('liverequests.html', all_requests=all_requestss)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\onely\app\templates\liverequests.html", line 6, in top-level template code
    <link rel="stylesheet" href="{{ url_for('', filename='styles.css') }}">
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '' with values ['filename']. Did you mean 'bootstrap.static' instead?
2021-09-29 12:27:33,253 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-09-29 12:27:45,001 ERROR: Exception on /liverequests [GET] [in c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\xampp\htdocs\onely\app\main\routes.py", line 55, in liverequests
    return render_template('liverequests.html', all_requests=all_requestss)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\xampp\htdocs\onely\app\templates\liverequests.html", line 6, in top-level template code
    <link rel="stylesheet" href="{{ url_for('', filename='styles.css') }}">
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\flask\helpers.py", line 326, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\fb\appdata\local\programs\python\python37\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '' with values ['filename']. Did you mean 'bootstrap.static' instead?
2021-09-29 12:28:43,204 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-09-29 12:32:14,940 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-10-28 15:08:32,028 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-10-28 15:16:28,905 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
2021-10-28 15:17:02,840 INFO: Strefi startup [in C:\xampp\htdocs\onely\app\__init__.py:90]
